# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/custom-gcl.jsonschema.json

version: v2.10.1

plugins:
  - module: 'github.com/manakovpavel1997-lab/logchecklint'
    import: 'github.com/manakovpavel1997-lab/logchecklint'
    path: .
